# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
defaults: &defaults
  docker:
    - image: circleci/ruby:2.4.2

cache_gem: &cache_gem
  key: gems-v1-{{ checksum "Gemfile.lock" }}

version: 2

general:
  branches:
    only:
      - develop

jobs:
  build:
    <<: *defaults
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - checkout
      - restore_cache: *cache_gem
      - run: bundle install --deployment
      - save_cache: 
          <<: *cache_gem
          paths:
            - vendor/bundle
      - run: bundle exec jekyll build
      - persist_to_workspace:
          root: _site
          paths:
            - ./*

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *cache_gem
      - run: bundle install --deployment
      - attach_workspace:
          at: _site
      - run: bundle exec htmlproofer ./_site --check-html

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: |
          git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
          git config --global user.email "${CIRCLE_PROJECT_USERNAME}@${CIRCLE_PROJECT_USERNAME}"
      - attach_workspace:
          at: _site
      - run: |
          git fetch origin
          git checkout master
          cp -av _site/* .
          rm -rf _site
          git add .
          git commit -a -m "Deploy ${CIRCLE_BUILD_NUM}"
      - run:
          git push origin master
 

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test

